apps/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('members',include('members.urls')),
    path('', include('customers.urls')),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

handler404="customers.views.handler404"
handler500="customers.views.handler500"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path ,reverse_lazy
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'customers'
urlpatterns = [
    path('', views.Mainview.as_view(), name='index'),
    path('/post/create',
        views.PostCreateView.as_view(success_url=reverse_lazy('customers:index')), name='post_create'),
    path('like/<int:pk>',views.Likeview, name="like_post"),
    path('/post/delete/<int:pk>',
        views.DeletePost.as_view(success_url=reverse_lazy('customers:index')), name='post_delete'),
    path('post/ajax/create',views.post_create , name='post_create_ajax'),
    path('comment/ajax/create',views.commentcreate , name='comment_create_ajax'),
    path('test',views.Testview , name='test-view'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'members'
urlpatterns = [
    path('/login', views.login_user, name='login'),
    path('/logout', views.logout_user, name='logout'),
    path('/register', views.register_user, name='register'),
    path('/follow', views.follwingview, name='follow'),
    path('/profile/<slug:slug>',views.UserProfiles.as_view(),name="users-profile"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    ,blank=True)
    text = models.TextField(blank=True,null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Comment', related_name='comments_owned')
    main_img = models.ImageField(upload_to='images/',null=True, blank=True)   
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User,related_name="post_likes",blank=True)
    #shows The likes numbers
    def number_of_likes(self):
        return self.likes.count()

    def comments_list(self):
        return self.comments.all()
    
    #returns the publish date
    def publish_date(self):
        return self.updated_at.strftime("%b-%Y")
    # Shows up in the admin list
    def __str__(self):
        return self.text


class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11]


class StoryModel(models.Model):
        user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='story_user')
        content = models.ImageField(upload_to='images/')
        caption = models.TextField(max_length=50)
        expired = models.BooleanField(default=False)
        posted = models.DateTimeField(auto_now_add=True)

        def __str__(self):
            return self.user.username

customers/forms.py
from django import forms
from .models import Post ,Comment ,StoryModel

#strip to remove empty spaces
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)
    def __init__(self, *args, **kwargs):
        super(CreateForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = Comment
        fields = ['text']  # Picture is manual

class CreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CreateForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = Post
        fields = ['title', 'text','main_img']  # Picture is manual


class StoryForm(forms.Form):
    content=forms.ImageField(required=True)
    caption = forms.CharField(required=False,max_length=50,strip=True)

    class Meta : 
        model = StoryModel 
        fields = ['content','caption']
        

customers/views.py
from django.views import View
from django.urls import reverse ,reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.template import RequestContext
from django.contrib.auth.models import User
from django_user_agents.utils import get_user_agent
from django.http import JsonResponse
from django.core import serializers

from .models import Post,Comment ,StoryModel
from members.models import Profile,Follwing_count
from .forms import CommentForm,CreateForm , StoryForm
from .owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
# Create your views here.

class Mainview(OwnerListView):
    model=Post
    template_name='customers/index.html'

    def get(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            posts=Post.objects.all().order_by('-created_at')
            profiles=Profile.objects.all()
            #getting the user browser info
            user_agent = get_user_agent(request).browser.family
            #passing the create form to the main page
            create_form = CreateForm()

            followers_posts_list = {}
            try:
                userobject = get_object_or_404(Profile, user=self.request.user)
                followers=Follwing_count.objects.filter(follwer=userobject.user)
                following = len(Follwing_count.objects.filter(follwing=userobject.user))
                follower_count = len(followers)
                for follower in followers :
                    user_object = User.objects.get(username=follower)
                    followers_posts_list=Post.objects.filter(owner=user_object)
            except:
                pass
            if followers_posts_list:
                context = {'profile_list':profiles,'post_list':posts,'user_agent':user_agent,'create_form':create_form,
                'followers_posts_list':followers_posts_list,'following':following , 'followers':follower_count}
            else:
                context = {'profile_list':profiles,'post_list':posts,'user_agent':user_agent,'create_form':create_form}
            return render(request,'customers/index.html',context)
        else :
            return render(request,'members/login.html')


class PostDetail(OwnerDetailView):               
    model= Post
    template_name='customers/main.html'
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        likes_connected = get_object_or_404(Post, id=self.kwargs['pk'])
        liked = False
        if likes_connected.likes.filter(id=self.request.user.id).exists():
            liked = True
        data['number_of_likes'] = likes_connected.number_of_likes()
        data['post_is_liked'] = liked
        return data


    

#standard way of creating the Post
class PostCreateView(LoginRequiredMixin, View):
    template_name = 'customers/create.html'
    success_url = reverse_lazy('customers:index')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving pic = form.save(commit=False)
        pic = form.save(commit=False)
        pic.owner = self.request.user
        pic.save()
        
        return redirect(self.success_url)

def Likeview(request,pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    ctx = {}
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        ctx = {'liked':False}
    else:
        post.likes.add(request.user)
        ctx = {'liked':True}
    return HttpResponseRedirect(reverse('customers:test-view'),ctx)

class DeletePost(OwnerDeleteView):
    model = Post
    template_name = 'customers/delete_post.html'
    success_message ='The Post was successfully deleted!'

def handler404(request,exception, *args, **argv):
    return render(request,'404.html', {})

def handler500(request, *args, **argv):
    return render(request,'404.html', {})


#creating the post using jquery and ajax and making it serialized
def post_create(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        print("success!")
        if request.method == "POST":
            post= request.POST["message"]
            new_post =Post.objects.create(text=post,owner=request.user)
            res= serializers.serialize('json',[new_post,])
            return JsonResponse({"instance": res}, status=200)
        else:
             return JsonResponse({"error": request.errors}, status=400)
    return JsonResponse({"error": ""}, status=400)


def commentcreate(request  ):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        print("success!")
        if request.method == "POST":
            pk= request.POST["post-id"]
            post = get_object_or_404(Post,id=pk)
            comment_text = request.POST["comment-message"]
            comment= Comment.objects.create(text=comment_text,owner=request.user,post=post)
            ser=serializers.serialize('json', [ comment, ])
            return JsonResponse({"instance": ser}, status=200)
        else:
            return JsonResponse({"error": request.errors}, status=400)
    return JsonResponse({"error": ""}, status=400)



def Testview(request):
    if request.user.is_authenticated :
        posts=Post.objects.all().order_by('-created_at')
        profiles=Profile.objects.all()
        user_agent = get_user_agent(request).browser.family
        comments = Comment.objects.all()
        #passing the create form to the main page
        create_form = CreateForm()
        followers_posts_list = {}
        try:
            userobject = get_object_or_404(Profile, user=request.user)
            followers=Follwing_count.objects.filter(follwer=userobject.user)
            following = len(Follwing_count.objects.filter(follwing=userobject.user))
            follower_count = len(followers)
            for follower in followers :
                user_object = User.objects.get(username=follower)
                followers_posts_list=Post.objects.filter(owner=user_object)
        except:
            pass
        if followers_posts_list:
            context = {'profile_list':profiles,'post_list':posts,'user_agent':user_agent,'create_form':create_form,
                'followers_posts_list':followers_posts_list,'following':following , 'followers':follower_count,'comments':comments}
        else:
            context = {'profile_list':profiles,'post_list':posts,'user_agent':user_agent,'create_form':create_form,'following':following , 
                    'followers':follower_count,'comments':comments,'users':followers}
        return render(request,'navbar.html',context)
    else : 
        return render(request,'members/register.html')



    
def CreateStory(request):
    if request.method == "POST":
        form = StoryForm(request.POST,request.FILES or None)
        if form.is_valid():
            image= request.FILES.get('content')
            caption = request.cleaned_data.get('caption')
            story = StoryModel(user=request.user,content=image,caption=caption)
            story.save()
            return redirect()

        

customers/templates/base.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->

<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" 
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
    crossorigin="anonymous">
    <link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"
    crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">


{% block head %} {% endblock %}

</head>
<body>
{% block navbar %} {% endblock %}

<div class="container-fluid mt-5">

{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
<div class="sidenav">
    <a href="#about">About</a>
    <a href="#services">Services</a>
    <a href="#clients">Clients</a>
    <a href="#contact">Contact</a>
  </div>   
<div class="row flex-xl-nowrap">   

</div>
{% block content %}
{% endblock %}
</div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" 
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" 
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% block javascript %}
{% endblock javascript %}

{% block footer %} {% endblock %}
</body>
</html>

customers/templates/base_nav.html
{% extends "base.html" %}
{% block navbar %}
<!-- <nav class="navbar navbar-light justify-content-between" style="background-color: #006ebd;">
 <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>

    </div>
   
    <ul class="nav navbar-nav navbar-left">
      {% url 'customers' as main %}
      <li {% if request.get_full_path == main %} class="nav navbar-nav navbar-left active"{% endif %}>
          <a href="{% url 'customers:index' %}">Social media </a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <form class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        {% if user.is_authenticated %}
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <img style="width: 25px;" src="{{ user.profile.profile_pic.url }}"/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="#" class="notification">
                    <span>Inbox</span>
                    <span class="badge">3</span>
                  </a></li>
                <li><a href="{% url 'members:users-profile' user.profile.slug %}">Profile</a></li>
                <li><a href="{% url 'members:logout' %}?next={% url 'customers:index' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'members:login' %}?next={% url 'customers:index' %}">Login</a>
        </li>
        {% endif %}
    </ul>

  </div>
</nav>
 -->

<header class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar">
 <nav class="navbar navbar-icon-top navbar-expand-lg fixed-top navbar-dark bg-primary">
  <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown" >
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bars"></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <div class="sidebar">
            <div class="d-flex justify-content-center">
              <img style="width: 50px;" src="{{ user.profile.profile_pic.url }}"/>
            </br></div>
            <div class="profile d-flex justify-content-center" >
            </br><b>Welcome {{ user.username }}</b></br> </div>
            <hr>
            <a href="{% url 'members:users-profile' user.profile.slug %}"><i class="fa fa-fw fa-user"></i> Profile</a>
            <a href="#contact"><i class="fa fa-fw fa-envelope">
              <span class="badge badge-warning">11</span>
            </i> Messeges</a>
            <a href="#home"><i class="fa fa-fw fa-home"></i> Home</a>
            <a href="{% url 'members:logout' %}?next={% url 'customers:index' %}">
              <i class="fa fas fa-sign-out-alt">
              </i>
              Logout
            </a>
          </div>
        </div>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'customers:index' %}">
          <i class="fa fa-home"></i>
          Social media
          <span class="sr-only">(current)</span>
          </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fa fa-envelope-o">
            <span class="badge badge-danger">11</span>
          </i>
          Link
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">
          <i class="fa fa-envelope-o">
            <span class="badge badge-warning">11</span>
          </i>
          Disabled
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-envelope-o">
            <span class="badge badge-primary">11</span>
          </i>
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    
    <ul class="navbar-nav ">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'members:logout' %}?next={% url 'customers:index' %}">
          <i class="fa fas fa-sign-out-alt">
          </i>
          Logout
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'members:login' %}?next={% url 'customers:index' %}">
          <i class="fa fas fa-sign-in-alt">
          </i>
          Login
        </a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</header>


{% endblock %}

customers/templates/footer.html
{% load static %}
<footer>
    <p>Social Network created By @Abdul<br>
    <a href="https://github.com/Abdul88dev">Abdul88dev</a></p>
  </footer>