apps/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('members',include('members.urls')),
    path('', include('customers.urls')),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

handler404="customers.views.handler404"
handler500="customers.views.handler500"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path ,reverse_lazy
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'customers'
urlpatterns = [
    path('', views.Mainview.as_view(), name='index'),
    path('/post/create',
        views.PostCreateView.as_view(success_url=reverse_lazy('customers:index')), name='post_create'),
    path('like/<int:pk>',views.Likeview, name="like_post"),
    path('/post/delete/<int:pk>',
        views.DeletePost.as_view(success_url=reverse_lazy('customers:index')), name='post_delete'),
    path('post/ajax/create',views.post_create , name='post_create_ajax'),
    path('comment/ajax/create',views.commentcreate , name='comment_create_ajax'),
    path('test',views.Testview , name='test-view'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'members'
urlpatterns = [
    path('/login', views.login_user, name='login'),
    path('/logout', views.logout_user, name='logout'),
    path('/register', views.register_user, name='register'),
    path('/follow', views.follwingview, name='follow'),
    path('/profile/<slug:slug>',views.UserProfiles.as_view(),name="users-profile"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    ,blank=True)
    text = models.TextField(blank=True,null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Comment', related_name='comments_owned')
    main_img = models.ImageField(upload_to='images/',null=True, blank=True)   
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User,related_name="post_likes",blank=True)
    #shows The likes numbers
    def number_of_likes(self):
        return self.likes.count()

    def comments_list(self):
        return self.comments.all()
    
    #returns the publish date
    def publish_date(self):
        return self.updated_at.strftime("%b-%Y")
    # Shows up in the admin list
    def __str__(self):
        return self.text


class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11]


class StoryModel(models.Model):
        user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='story_user')
        content = models.ImageField(upload_to='images/')
        caption = models.TextField(max_length=50)
        expired = models.BooleanField(default=False)
        posted = models.DateTimeField(auto_now_add=True)

        def __str__(self):
            return self.user.username

customers/forms.py
from django import forms
from .models import Post ,Comment ,StoryModel

#strip to remove empty spaces
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)
    def __init__(self, *args, **kwargs):
        super(CreateForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = Comment
        fields = ['text']  # Picture is manual

class CreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CreateForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = Post
        fields = ['title', 'text','main_img']  # Picture is manual


class StoryForm(forms.Form):
    content=forms.ImageField(required=True)
    caption = forms.CharField(required=False,max_length=50,strip=True)

    class Meta : 
        model = StoryModel 
        fields = ['content','caption']
        

customers/views.py
from django.views import View
from django.urls import reverse ,reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.template import RequestContext
from django.contrib.auth.models import User
from django_user_agents.utils import get_user_agent
from django.http import JsonResponse
from django.core import serializers

from .models import Post,Comment ,StoryModel
from members.models import Profile,Follwing_count
from .forms import CommentForm,CreateForm , StoryForm
from .owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
# Create your views here.

class Mainview(OwnerListView):
    model=Post
    template_name='customers/index.html'

    def get(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            posts=Post.objects.all().order_by('-created_at')
            profiles=Profile.objects.all()
            #getting the user browser info
            user_agent = get_user_agent(request).browser.family
            #passing the create form to the main page
            create_form = CreateForm()

            followers_posts_list = {}
            try:
                userobject = get_object_or_404(Profile, user=self.request.user)
                followers=Follwing_count.objects.filter(follwer=userobject.user)
                following = len(Follwing_count.objects.filter(follwing=userobject.user))
                follower_count = len(followers)
                for follower in followers :
                    user_object = User.objects.get(username=follower)
                    followers_posts_list=Post.objects.filter(owner=user_object)
            except:
                pass
            if followers_posts_list:
                context = {'profile_list':profiles,'post_list':posts,'user_agent':user_agent,'create_form':create_form,
                'followers_posts_list':followers_posts_list,'following':following , 'followers':follower_count}
            else:
                context = {'profile_list':profiles,'post_list':posts,'user_agent':user_agent,'create_form':create_form}
            return render(request,'customers/index.html',context)
        else :
            return render(request,'members/login.html')


class PostDetail(OwnerDetailView):               
    model= Post
    template_name='customers/main.html'
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        likes_connected = get_object_or_404(Post, id=self.kwargs['pk'])
        liked = False
        if likes_connected.likes.filter(id=self.request.user.id).exists():
            liked = True
        data['number_of_likes'] = likes_connected.number_of_likes()
        data['post_is_liked'] = liked
        return data


    

#standard way of creating the Post
class PostCreateView(LoginRequiredMixin, View):
    template_name = 'customers/create.html'
    success_url = reverse_lazy('customers:index')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving pic = form.save(commit=False)
        pic = form.save(commit=False)
        pic.owner = self.request.user
        pic.save()
        
        return redirect(self.success_url)

def Likeview(request,pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    ctx = {}
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        ctx = {'liked':False}
    else:
        post.likes.add(request.user)
        ctx = {'liked':True}
    return HttpResponseRedirect(reverse('customers:test-view'),ctx)

class DeletePost(OwnerDeleteView):
    model = Post
    template_name = 'customers/delete_post.html'
    success_message ='The Post was successfully deleted!'

def handler404(request,exception, *args, **argv):
    return render(request,'404.html', {})

def handler500(request, *args, **argv):
    return render(request,'404.html', {})


#creating the post using jquery and ajax and making it serialized
def post_create(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        print("success!")
        if request.method == "POST":
            post= request.POST["message"]
            new_post =Post.objects.create(text=post,owner=request.user)
            res= serializers.serialize('json',[new_post,])
            return JsonResponse({"instance": res}, status=200)
        else:
             return JsonResponse({"error": request.errors}, status=400)
    return JsonResponse({"error": ""}, status=400)


def commentcreate(request  ):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        print("success!")
        if request.method == "POST":
            pk= request.POST["post-id"]
            post = get_object_or_404(Post,id=pk)
            comment_text = request.POST["comment-message"]
            comment= Comment.objects.create(text=comment_text,owner=request.user,post=post)
            ser=serializers.serialize('json', [ comment, ])
            return JsonResponse({"instance": ser}, status=200)
        else:
            return JsonResponse({"error": request.errors}, status=400)
    return JsonResponse({"error": ""}, status=400)



def Testview(request):
    if request.user.is_authenticated :
        posts=Post.objects.all().order_by('-created_at')
        profiles=Profile.objects.all()
        user_agent = get_user_agent(request).browser.family
        comments = Comment.objects.all()
        #passing the create form to the main page
        create_form = CreateForm()
        followers_posts_list = {}
        try:
            userobject = get_object_or_404(Profile, user=request.user)
            followers=Follwing_count.objects.filter(follwer=userobject.user)
            following = len(Follwing_count.objects.filter(follwing=userobject.user))
            follower_count = len(followers)
            for follower in followers :
                user_object = User.objects.get(username=follower)
                followers_posts_list=Post.objects.filter(owner=user_object)
        except:
            pass
        if followers_posts_list:
            context = {'profile_list':profiles,'post_list':posts,'user_agent':user_agent,'create_form':create_form,
                'followers_posts_list':followers_posts_list,'following':following , 'followers':follower_count,'comments':comments}
        else:
            context = {'profile_list':profiles,'post_list':posts,'user_agent':user_agent,'create_form':create_form,'following':following , 
                    'followers':follower_count,'comments':comments,'users':followers}
        return render(request,'navbar.html',context)
    else : 
        return render(request,'members/register.html')



    
def CreateStory(request):
    if request.method == "POST":
        form = StoryForm(request.POST,request.FILES or None)
        if form.is_valid():
            image= request.FILES.get('content')
            caption = request.cleaned_data.get('caption')
            story = StoryModel(user=request.user,content=image,caption=caption)
            story.save()
            return redirect()

        

customers/templates/customers/create.html
{% extends "base_nav.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

customers/templates/customers/delete_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body 
 onload="document.deleteform.submit()">
    <form action="" name="deleteform" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
      </form>
</body>
</html>

customers/templates/customers/index.html
{% extends "base_nav.html" %}
{% load static %}
{% load user_agents %}
{% block head %} 
<script >
    setTimeout(() => {
      const box = document.getElementById('mydiv');
    
      // 👇️ hides element (still takes up space on page)
      box.style.visibility = 'hidden';
    }, 1000);
    </script>

{% endblock %}
{% block content %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-primary" id="mydiv" role="alert">
    {{ message }}
</div>
    {% endfor %}
    {% endif %} 

      
    {% if user.is_authenticated %}

    <!-- adding a post area -->
    <section class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <!-- CUSTOM BLOCKQUOTE -->
                    <blockquote class="blockquote blockquote-custom bg-white p-5 shadow rounded">
                        <div class="blockquote-custom-icon"><i class="fa fad fa-quote-right"></i></div>
                        <p class="mb-0 mt-2 font-italic">    
                            <form id="post_create_form" method="post">
                            <div class="row">
                                {% csrf_token %}
                                {% for field in create_form %}
                                        <div class="form-group col-4">
                                            <label class="col-12">{{ field.label }}</label>
                                            {{ field }}
                                        </div>
                                {% endfor %}
                                        <input type="submit" class="btn btn-primary" value="Create a post" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </blockquote><!-- END -->
    
                </div>
            </div>
        </div>
    </section>
    <!-- end of adding a post -->
    {% endif %}

<!-- {% if post_list %}
    {% for post in post_list %}
        <p>
            <div class="media">
            <img class="align-self-start mr-3" src="{{ post.owner.profile.profile_pic.url }}" width="25" height="25" alt="Generic placeholder image"/>
             <b><a href="{%  url 'members:users-profile' post.owner.profile.slug %}" >{{ post.owner.username }}</a></b><br/>
            {{ post.title }}<br/>
            <div class="media-body">{{ post.text }} <br/>
            </div>
            {% if post.owner == user %}
            <p>( <a href="{% url 'customers:post_delete' post.id %}">Delete</a>)</p>
            {% endif %}
            
                {% if user.is_authenticated %}
                <form action="{% url 'customers:like_post' post.id %}" method="POST">
                {% csrf_token %}
                {% if user not in post.likes.all %}
                <button type="submit" name="post_id" value="{{post.id}}" class ="like-post-button"><img src="{% static '/images/like.png' %}" width="25" height="25"></button>
                {% else %}
                <button type="submit" name="post_id" value="{{post.id}}" class ="like-post-button" ><img src="{% static '/images/unlike.png' %}" width="25" height="25"/></button>
                {% endif %}
                </form>
                {% endif %}
                <strong class="text-secondary">{{ post.number_of_likes }} Like{{ number_of_likes|pluralize }}</strong>
                        </p>
                    </div>
    {% endfor %}
{% endif %} -->
<!-- #region of post of the following-->
{% if followers_posts_list %}
    {% for post in followers_posts_list%}
            {{ post.title }} </br>
            {{ post.text }}
    {% endfor %}
{% endif %}
<!--this part is for testing the layout-->
{% if post_list %}
{% for post in post_list %}

<div class="container mt-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-8" id="post-section">
            <div class="d-flex flex-column comment-section" id="{{post.id}}myGroup">
                <div class="bg-white p-2">
                    <div class="d-flex flex-row user-info"><img class="rounded-circle" src="{{ post.owner.profile.profile_pic.url }}" width="40" height="40">
                        <div class="d-flex flex-column justify-content-start ml-2"><span class="d-block font-weight-bold name"><a href="{%  url 'members:users-profile' post.owner.profile.slug %}" >{{ post.owner.username }}</a>
                        </span><span class="date text-black-50">Shared publicly - {{ post.publish_date }}</span></div>
                    </div>
                    <div class="mt-2">
                        <p class="comment-text" width="100%">{{ post.text }} </p>
                    </div>
                </div>
                <div class="bg-white p-2">
                    <div class="d-flex flex-row fs-12">
                        <!-- LIKES -->
                {% if user.is_authenticated %}
                <form action="{% url 'customers:like_post' post.id %}" method="POST">
                {% csrf_token %}
                {% if user not in post.likes.all %}
                <button type="submit" name="post_id" value="{{post.id}}" class ="like-post-button"><img src="{% static '/images/like.png' %}" width="25" height="25"></button>
                {% else %}
                <button type="submit" name="post_id" value="{{post.id}}" class ="like-post-button" ><img src="{% static '/images/unlike.png' %}" width="25" height="25"/></button>
                {% endif %}
                </form>
                {% endif %}
                <strong class="text-secondary">{{ post.number_of_likes }} Like{{ number_of_likes|pluralize }}</strong>
                        </p>
                        <div class="like p-2 cursor action-collapse" data-toggle="collapse" aria-expanded="true" aria-controls="collapse-1" href="#{{post.id}}collapse-1"><i class="fa fa-commenting-o"></i><span class="ml-1">Comment</span></div>
                        <div class="like p-2 cursor action-collapse" data-toggle="collapse" aria-expanded="true" aria-controls="collapse-2" href="#{{post.id}}collapse-2"><i class="fa fa-share"></i><span class="ml-1">Share</span></div>
                    </div>
                </div>
                <div id="{{post.id}}collapse-1" class="bg-light p-2 collapse" data-parent="#{{post.id}}myGroup" >
                    <div class="d-flex flex-row align-items-start"><img class="rounded-circle" src="{{ post.owner.profile.profile_pic.url }}" width="40"><textarea class="form-control ml-1 shadow-none textarea"></textarea></div>
                    <div class="mt-2 text-right"><button class="btn btn-primary btn-sm shadow-none" type="button">Post comment</button><button class="btn btn-outline-primary btn-sm ml-1 shadow-none" type="button">Cancel</button></div>
                </div>
                <div id="{{post.id}}collapse-2" class="bg-light p-2 collapse" data-parent="#{{ post.id }}myGroup">
                    <div class="d-flex flex-row align-items-start"><i class="fa fa-facebook border p-3 rounded mr-1"></i><i class="fa fa-twitter border p-3 rounded mr-1"></i><i class="fa fa-linkedin border p-3 rounded mr-1"></i><i class="fa fa-instagram border p-3 rounded mr-1"></i><i class="fa fa-dribbble border p-3 rounded mr-1"></i>
                        <i
                            class="fa fa-pinterest-p border p-3 rounded mr-1"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--end the part  for testing the layout-->
{% endfor %}
{% endif %}


{% endblock %}
{% block javascript %}
<script>
    /*
        On submiting the form, send the POST ajax
        request to server and after successfull submission
        display the object.
    */
    $("#post_create_form").submit(function (e) {
        // preventing from page reload and default actions
        e.preventDefault();
        // serialize the data for sending the form data.
        var serializedData = $(this).serialize();
        // make POST ajax call
        $.ajax({
            type: 'POST',
            url: "{% url 'customers:post_create_ajax' %}",
            data: serializedData,
            headers: {
                "X-Requested-With": "XMLHttpRequest"
                     },
            success: function (response) {
                // on successfull creating object
                // 1. clear the form.
                $("#post_create_form").trigger("reset");
                // display the newly friend to table.
                //var instance = JSON.parse(response["instance"]);
                //var fields = instance[0]["fields"];
                //$("#my_friends tbody").prepend(
                /*     `<tr>
                    <td>${fields["nick_name"]||""}</td>
                    <td>${fields["first_name"]||""}</td>
                    <td>${fields["last_name"]||""}</td>
                    <td>${fields["likes"]||""}</td>
                    <td>${fields["dob"]||""}</td>
                    <td>${fields["lives_in"]||""}</td>
                    </tr>`
                ) */
            },
            error: function (response) {
                // alert the error if any error occured
                alert(response["responseJSON"]["error"]);
            }
        })
    })
</script>
{% endblock javascript %}