apps/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('members',include('members.urls')),
    path('', include('customers.urls')),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

handler404="customers.views.handler404"
handler500="customers.views.handler500"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path ,reverse_lazy
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'customers'
urlpatterns = [
    path('', views.Mainview.as_view(), name='index'),
    path('/post/create',
        views.PostCreateView.as_view(success_url=reverse_lazy('customers:index')), name='post_create'),
    path('like/<int:pk>',views.Likeview, name="like_post"),
    path('/post/delete/<int:pk>',
        views.DeletePost.as_view(success_url=reverse_lazy('customers:index')), name='post_delete'),
    path('post/ajax/create',views.post_create , name='post_create_ajax'),
    path('comment/ajax/create',views.commentcreate , name='comment_create_ajax'),
    path('test',views.Testview , name='test-view'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'members'
urlpatterns = [
    path('/login', views.login_user, name='login'),
    path('/logout', views.logout_user, name='logout'),
    path('/register', views.register_user, name='register'),
    path('/follow', views.follwingview, name='follow'),
    path('/profile/<slug:slug>',views.UserProfiles.as_view(),name="users-profile"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from customers.models import Post
import random 
import string 



class Profile(models.Model):
    GENDER = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    bio = models.TextField(max_length=2000,null=True)
    birthday = models.DateField(null=True)
    profile_pic=models.ImageField(default='default.png',upload_to='profile-images')
    gender = models.CharField(max_length=1, choices=GENDER,blank=True)
    slug = models.SlugField(null=True)




    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.profile_pic.path)

        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.profile_pic.path)
    
    #def create_slug(size=10, chars=string.ascii_lowercase + string.digits):
        #return ''.join(random.choice(chars) for _ in range(size))

    def __str__(self):
        return self.user.username+" Profile"

class Follwing_count(models.Model):
    follwer = models.CharField(max_length=100)
    follwing = models.CharField(max_length=100)

    def __str__(self):
        return self.follwing +" followed By "+ self.follwer

class Agent(models.Model):
    user =   models.OneToOneField(User,on_delete=models.CASCADE)
    agent =  models.CharField(max_length=100)

    def __str__(self) :
        return self.agent


class Notifecation(models.Model):
    NOTIFECATION_TYPE = (('C','Comment'),('F','Follow'),('L','Like'))

    post= models.ForeignKey(Post , on_delete=models.CASCADE,related_name='post_notification',blank=True)
    notifier = models.ForeignKey(User,on_delete=models.CASCADE,related_name='notification_sender')
    notified = models.ForeignKey(User,on_delete=models.CASCADE,related_name='notification_reciever')
    type = models.CharField(max_length=1 , choices=NOTIFECATION_TYPE)
    date = models.DateTimeField(auto_now_add=True)
    seen = models.BooleanField(default=False)

members/views.py
from django.shortcuts import render ,redirect ,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .models import Profile ,Follwing_count
from django.views.generic import DetailView ,ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from unidecode import unidecode
from django.template.defaultfilters import slugify
import string ,random
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

def login_user(request):
    if request.user.is_authenticated:
        messages.add_message(request, messages.INFO, 'You Are already signed in')
        return redirect('/')
    else:
        if request.method =="POST":
            username = request.POST["username"]
            password = request.POST["password"]
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request,user)
                
                return redirect('/')
            else :
                messages.add_message(request, messages.INFO, 'There was a problem loging in Try Again')
                return render(request,'members/login.html',{})
        else :
            return render(request,'members/login.html',{})


def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        messages.add_message(request, messages.INFO, 'You Are Signed out or Not Registered')
        return redirect('/')
    else:
        return redirect('/')


def register_user(request):
        if request.method == "POST":
            username = request.POST["username"]
            password = request.POST["password"]
            email    = request.POST["email"]
            user_exist = False
            try:
                User.objects.get(username=username)
                user_exist = True
            except:
                pass
            if not user_exist:
                user=User.objects.create_user(username=username,password=password,email=email)
                #char = string.ascii_lowercase
                #size = 10
                #letters = username+''.join(random.choice(char) for _ in range(size))
                #slug = slugify(unidecode(letters))
                #Profile.objects.create(user=user,slug=slug)
                login(request,user)
                return redirect('/')
            else :
                return render(request,'members/register.html',{})
        elif request.method == 'GET': 
            return render(request, 'members/register.html', {})

class UserProfile(LoginRequiredMixin,DetailView):
    model = Profile
    template_name = 'members/profile.html'
    

class UserProfiles(DetailView):
    model= Profile
    template_name = 'members/profile.html'
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        userobject = get_object_or_404(Profile, slug=self.kwargs['slug'])
        if Follwing_count.objects.filter(follwer=self.request.user.username,follwing=userobject.user.username):
            button_text = "Unfollow"
        else:
             button_text = "Follow"
        followers=Follwing_count.objects.filter(follwer=userobject.user)
        followers_count = Follwing_count.objects.filter(follwing=userobject.user)
        data['following'] = len(followers)
        data['followers'] = len(followers_count)
        data['button_text'] = button_text
        return data
    

def follwingview(request):
    if request.method == 'POST':
        follower = request.POST['follwer']
        following = request.POST['following']
        following_id = request.POST['follwingid']
        slug = Profile.objects.get(user=following_id)

        if Follwing_count.objects.filter(follwer=follower, follwing=following).first():
            delete_follower = Follwing_count.objects.get(follwer=follower, follwing=following)
            delete_follower.delete()
            return redirect('profile/'+slug.slug)
        else:
            new_follower = Follwing_count.objects.create(follwer=follower, follwing=following)
            new_follower.save()
            return redirect('profile/'+slug.slug)
    else:
        return redirect('/')

members/templates/members/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/3833c75b58.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Login</title>
    <style>


      html,
      body{

        margin: 0px;
  height: 100%;
      }
      #myForm {
  min-width: 500px;
  position: absolute;
  text-align: left;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size: 1rem;
  border-radius: 20px 20px 20px 20px;
  background-color: azure;
  box-shadow: #330000;
  padding:10px;
}

@media (max-width: 500px) {
  #myForm {
    min-width: 90%;
  }
}
.maincontainer{
  width :100%;
  height: 100%;
  background-color: #330000;
        background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100%25' height='100%25' viewBox='0 0 800 400'%3E%3Cdefs%3E%3CradialGradient id='a' cx='396' cy='281' r='514' gradientUnits='userSpaceOnUse'%3E%3Cstop offset='0' stop-color='%232011DD'/%3E%3Cstop offset='1' stop-color='%23330000'/%3E%3C/radialGradient%3E%3ClinearGradient id='b' gradientUnits='userSpaceOnUse' x1='400' y1='148' x2='400' y2='333'%3E%3Cstop offset='0' stop-color='%23FA3' stop-opacity='0'/%3E%3Cstop offset='1' stop-color='%23FA3' stop-opacity='0.5'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect fill='url(%23a)' width='800' height='400'/%3E%3Cg fill-opacity='0.4'%3E%3Ccircle fill='url(%23b)' cx='267.5' cy='61' r='300'/%3E%3Ccircle fill='url(%23b)' cx='532.5' cy='61' r='300'/%3E%3Ccircle fill='url(%23b)' cx='400' cy='30' r='300'/%3E%3C/g%3E%3C/svg%3E");
        background-attachment: fixed;
        background-size: cover;
}
.welcoming{
  position: absolute;
  top:30%;
  left:45%;
  font-size:large;
  font-weight: bold;
  color: whitesmoke;
}
footer {
  text-align: center;
  padding: 3px;
  background-color: DarkSalmon;
  color: white;
  bottom:0;
  position: absolute;
  width: 100%;
 /* set the bottom to 0*/
}
    </style>
</head>
<body>
<div class="maincontainer">
  <div class='container-fluid'>
<div class="welcoming">Members Login</div>
    <form  id="myForm" action="{% url 'members:login' %}" class="login100-form validate-form" method="POST" >
      <div class="form-group">
        {% csrf_token %} 
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label"><i class="fa fa-solid fa-user"></i> Username</label required>
          <input type="text" class="form-control" id="exampleInputEmail1" name="username" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label"><i class="fa fa-duotone fa-lock"></i> Password</label>
          <input type="password" class="form-control" name="password"  id="exampleInputPassword1" required>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
<hr>
<a class="btn btn-outline-dark" href="{% url 'social:begin' 'google-oauth2' %}" role="button" style="text-transform:none">
  <img width="20px" style="margin-bottom:3px; margin-right:5px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
  Login with Google
</a> 
<a href="{% url 'social:begin' 'github' %}">
  LOGIN WITH GITHUB 
</a>
<br>
        Not a member yet?! <a href="{% url 'members:register' %}">Sign up</a>
      </form>
    </div>
    </div>
    {% include 'footer.html' %}
</body>
</html>

members/templates/members/profile.html
{% extends "base_nav.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" type='text/css' href="{% static 'css/style.css' %}">
{% endblock %}
{% block content %}
    
</br>
Welcome to the profile {{ profile.user }}
{% if profile.user == user %}
</br>
Your Bio is
</br>
{% else %}
</br>
The Bio is
</br>
{% endif %}
{{ profile.bio }}
</br>

<img src="{{ profile.profile_pic.url }}" width="50" height="50"/>
{% if profile.user == user %}
<p>Edit Profile</p>
{% else %}
<form action="{% url 'members:follow' %}" method="POST" >
    {% csrf_token %}

    <input type="hidden" value="{{ user }}" name="follwer" />
    <input type="hidden" value="{{ profile.user.id }}" name="follwingid" />
    <input type="hidden" value="{{ profile.user }}" name="following" />
    {% if user in followers.all %}
    <button type="submit" class="follow" >{{ button_text }}</button>
    {% else %}
    <button type="submit" class="follow" >{{ button_text }}</button>
    {% endif %}
</form>
{% endif %}
{{ followers_count }}
{{ following }} <b>following</b>
{{ followers }} <b>followers</b>

<a href="{% url 'customers:post_create'  %}" >Post</a>

{% endblock %}

members/templates/members/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style>


      html,
      body{

        margin: 0px;
  height: 100%;
      }
      #myForm {
  min-width: 500px;
  position: absolute;
  text-align: left;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size: 1rem;
  border-radius: 20px 20px 20px 20px;
  background-color: azure;
  box-shadow: #330000;
  padding:10px;
}

@media (max-width: 500px) {
  #myForm {
    min-width: 90%;
  }
}
.maincontainer{
  width :100%;
  height: 100%;
  background-color: #330000;
        background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100%25' height='100%25' viewBox='0 0 800 400'%3E%3Cdefs%3E%3CradialGradient id='a' cx='396' cy='281' r='514' gradientUnits='userSpaceOnUse'%3E%3Cstop offset='0' stop-color='%232011DD'/%3E%3Cstop offset='1' stop-color='%23330000'/%3E%3C/radialGradient%3E%3ClinearGradient id='b' gradientUnits='userSpaceOnUse' x1='400' y1='148' x2='400' y2='333'%3E%3Cstop offset='0' stop-color='%23FA3' stop-opacity='0'/%3E%3Cstop offset='1' stop-color='%23FA3' stop-opacity='0.5'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect fill='url(%23a)' width='800' height='400'/%3E%3Cg fill-opacity='0.4'%3E%3Ccircle fill='url(%23b)' cx='267.5' cy='61' r='300'/%3E%3Ccircle fill='url(%23b)' cx='532.5' cy='61' r='300'/%3E%3Ccircle fill='url(%23b)' cx='400' cy='30' r='300'/%3E%3C/g%3E%3C/svg%3E");
        background-attachment: fixed;
        background-size: cover;
}
.welcoming{
  position: absolute;
  top:30%;
  left:45%;
  font-size:large;
  font-weight: bold;
  color: whitesmoke;
}
    </style>
    <title>Register</title>

</head>
<body>
  <div class="maincontainer">
    <div class='container-fluid'>
    <form id="myForm" action="{% url 'members:register' %}" class="login100-form validate-form" method="POST" >
        {% csrf_token %} 
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Username</label required>
          <input type="text" class="form-control" id="exampleInputEmail1" name="username" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">email</label required>
          <input type="text" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" class="form-control" name="password"  id="exampleInputPassword1" required>
        </div>
        <button type="submit" class="btn btn-primary">Sign Up</button>
        <hr>
        <center>OR</center><br>
<a class="btn btn-outline-dark" href="{% url 'social:begin' 'google-oauth2' %}" role="button" style="text-transform:none">
  <img width="20px" style="margin-bottom:3px; margin-right:5px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
  Login with Google
</a>
<br>
      </form>
      </div>
      </div>
{% include 'footer.html' %}
</body>
</html>